/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package govtschemeportal;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import govtschemeportal.Update_and_delete;
/**
 *
 * @author Atul
 */
public class Scheme extends javax.swing.JFrame {

    Update_and_delete up_and_del=new  Update_and_delete();
    /**
     * Creates new form Scheme
     */
    public Scheme() {
        initComponents();
     showdata_into_table();
     up_and_del.updatethedata();
    }


public ArrayList<Schememodalclass> schemedatatodisplay()
        {
            ArrayList<Schememodalclass> schemedata=new ArrayList();
            
            try{
                Dbconnect db = new Dbconnect();
                String sql="select * from scheme";
                 ResultSet rs=db.queryReturner(sql);
                
                Schememodalclass schememodal;
                
                while(rs.next())
                {
                    schememodal=new Schememodalclass(rs.getInt("scheme_no"),rs.getString("scheme_name"),rs.getString("sector"),
                            rs.getString("male"),rs.getString("female"),rs.getInt("income"),rs.getString("education"),rs.getString("caste"),rs.getString("description"));
                   schemedata.add(schememodal);
                }
//                
            }
            catch(Exception e)
            {
               
            }
            return schemedata;
            
        }


    
public void showdata_into_table()
{
    ArrayList<Schememodalclass> list=schemedatatodisplay();
    DefaultTableModel modal =(DefaultTableModel)table_display.getModel();
    Object[] row =new Object[9];
    for(int i=0;i<list.size();i++)
    { 
        row[0]=list.get(i).getScheme_no();
        row[1]=list.get(i).getScheme_name();
        row[2]=list.get(i).getSector();
        row[3]=list.get(i).getMale();
        row[4]=list.get(i).getFemale();
        row[5]=list.get(i).getIncome();
        row[6]=list.get(i).getEducation();
        row[7]=list.get(i).getCaste();
        row[8]=list.get(i).getDescription();
        modal.addRow(row);
    }
    
    
    
    
    
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_display = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        table_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scheme_no", "Scheme_name", "Sector", "male", "female", "income", "education", "caste", "description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_display);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Goverment Schemes ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 373, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(323, 323, 323))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_displayMouseClicked
        // TODO add your handling code here:
        int index=table_display.getSelectedRow();
        TableModel model=table_display.getModel();
        
        String schemeno1=model.getValueAt(index, 0).toString();
        String schemename1=model.getValueAt(index, 1).toString();
        String sector1=model.getValueAt(index, 2).toString();
       String male1=model.getValueAt(index, 3).toString();
       String female1=model.getValueAt(index, 4).toString();
       String income1=model.getValueAt(index, 5).toString();
       //String education1=model.getValueAt(index, 6).toString();
     // String caste1=model.getValueAt(index, 7).toString();
       String description1=model.getValueAt(index, 8).toString();
       
       up_and_del.setVisible(true);
       up_and_del.pack();
       up_and_del.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
       up_and_del.schemno1.setText(schemeno1);
       up_and_del.schemename1.setText(schemename1);
       up_and_del.sector1.setText(sector1);
       up_and_del.description1.setText(description1);
       up_and_del.income2.setText(income1);
       if(male1.equalsIgnoreCase("yes"))
       {
           up_and_del.male1.setSelected(true);
       }
       else
       {
           up_and_del.male1.setSelected(false);
       }
      
       if(female1.equalsIgnoreCase("yes"))
       {
           up_and_del.female1.setSelected(true);
       }
       else
       {
           up_and_del.female1.setSelected(false);
       }
      
       String education1=model.getValueAt(index, 6).toString();
           
        switch(education1)
        {
            case "10":
                up_and_del.education1.setSelectedIndex(0);
                break;
                case "12":
                up_and_del.education1.setSelectedIndex(1);
                break;
                case "Graduation":
                up_and_del.education1.setSelectedIndex(2);
                break;
        }
 

       String caste1=model.getValueAt(index, 7).toString();
        switch(caste1)
        {
            case "General":
                up_and_del.caste1.setSelectedIndex(0);
                break;
                case "Obc":
                up_and_del.caste1.setSelectedIndex(1);
                break;
                case "Sc":
                up_and_del.caste1.setSelectedIndex(2);
                break;
                case "St":
                up_and_del.caste1.setSelectedIndex(3);
                break;
        }

        
        
    }//GEN-LAST:event_table_displayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable table_display;
    // End of variables declaration//GEN-END:variables
}
